### ISSUE TITLE
Unsorted arrays do not seem to work correctly

### ISSUE THREAD

**Issue by mckillion23** [YuJianrong/fast-array-diff#1]
When I run the following code I expect the results to be empty however they are not:

```
const arrayDiff = require('fast-array-diff');

const result = arrayDiff.diff(
   [{ id: '1234' }, { id: '5678' }],
   [{ id: '5678' }, { id: '1234' }],
   areEqual,
);

function areEqual(objA, objB) {
    return objA.id === objB.id;
}
```

The result is: "{"removed":[{"id":"5678"}],"added":[{"id":"5678"}]}"

When the objects are sorted then it works as expected.

**Comment by YuJianrong** [comment]
@mckillion23 That's not how this module works. This module is used to figure out what operations we need to modify an array A to another array B, for example, to change array `['abc', 'def', 'ghi']` to `['def', 'abc', 'ghi']`:
![image](https://user-images.githubusercontent.com/176076/75367754-a7ed8300-5875-11ea-97ab-78d2a531da3e.png)
Two operations are requires:
1. Remove the line 2 (old `def`)
2. Append the `def` before the 1st line.

For you requirement (compare two array no matter what order is), you can do it by sorting two array and compare the elements one by one.
