### ISSUE TITLE
Applying a patch while maintaining an object reference

### ISSUE THREAD

**Issue by fredure** [YuJianrong/fast-array-diff#11]
Please analyze the possibility of not re-creating a new object when applying the patch. I want to keep the old reference to the object.

**Comment by YuJianrong** [comment]
@fredure Not sure what you mean. If the items of the array are objects, there is no new object created.
If you are talking about change on the original array, it does not look possible.

**Comment by YuJianrong** [comment]
Close it since no feedback for a long time.
