### ISSUE TITLE
Bug of `diff`

### ISSUE THREAD

**Issue by yaofly2012** [YuJianrong/fast-array-diff#120]
# Steps to reproduce
```js
import { diff } from "fast-array-diff";

const oldArray = [
  {
    name: "Lucy"
  },
  {
    name: "Tom"
  }
];

const newArray = [
  {
    name: "Tom"
  },
  {
    name: "Lucy"
  }
];

const compare = (a, b) => a.name === b.name;

console.log(diff(oldArray, newArray, compare));
```

# What is expected?
```js
{
  added: [],
  removed: []
}
```

# What is actually happening?
```js
{
  added: [{ name: 'Tom'  }],
  removed: [{ name: 'Tom' }]
}
```
<img width="302" alt="image" src="https://user-images.githubusercontent.com/6823623/212867548-45553e0d-8635-4b98-bda6-ee02a87e393f.png">

|Environment|Info|
|--|--|
|fast-array-diff| v1.0.1|

**Comment by YuJianrong** [comment]
@yaofly2012 It's not a bug. This package is used to find the diff between two **sequences**, so the order matters. The array `[1, 2]` is different to array `[2, 1]`. I guess you're looking for something to find the diff between two sets, which is not what this package created for.
