### ISSUE TITLE
Diff on objects string attribute

### ISSUE THREAD

**Issue by bram2202** [YuJianrong/fast-array-diff#210]
Im using the lib find find differences between objects.
When i compare with numbers it works as intended but when i want to compare with strings or bools something strange happens.

**Example**:
``` TS
    const arr1 = [
      {
        id: "1",
        description: "1",
        blaat: "blaat",
        active: true
      },
      {
        id: "2",
        description: "2",
        blaat: "blaat",
        active: true
      }
    ];

    const arr2 = [
      {
        id: "1",
        description: "1",
        blaat: "blaat",
        active: true
      },
      {
        id: "2",
        description: "2",
        blaat: "blaat",
        active: true

      },
      {
        id: "3",
        description: "3",
        blaat: "blaat",
        active: true
      }
    ];

    const diff1 = diff(arr1, arr2, (a, b) => a.description === b.description);
    const diff2 = diff(arr1, arr2, (a, b) => a.blaat === b.blaat);

```
You would images both `diff1` and `diff2` are the same because in both cases an extra object was added to arr2.

But this is the response :

```
diff1
{
 added: [
  {
    id: '3',
    description: '3',
    blaat: 'blaat',
    active: true
  }
 ],
 removed: []
}
``` 

```
diff2
{
 added: [
  {
    id: '1',
    description: '1',
    blaat: 'blaat',
    active: true
  }
 ],
 removed: []
}
``` 

The first diff is comparing on `description` containing a number, and returns object with ID 3, and this is correct.
The second diff is comparing on `blaat` containing a text, but this returns object with ID 1, that exists in both array's.

Same issue is when comparing on `active` which is a bool

Am i missing something?

**Comment by YuJianrong** [comment]
@bram2202 
I think you misunderstand the means of diff of the arrays. This module is trying to find the difference between two sequences, for example:

From `'AA'` to `'AAA'`, the smallest editing is one action: (1) append an `'A'`on end, or (2) add `'A'` at begging, or (2) inset `'A'` in the middle. We should not do something like: append `'AB'` on the end then remove the last `'B'`, which is three character actions.

This module is used to find this case, not find the new items or missing items in a set.
