### ISSUE TITLE
Value is re-added when applying patch

### ISSUE THREAD

**Issue by master-elodin** [YuJianrong/fast-array-diff#3]
I've got two arrays like this:

```javascript
const oldVal = ['item1', 'item2', 'item3'];
const newVal = ['item4', 'item2', 'item3', 'foo'];
```

Running `diff.getPatch(oldVal, newVal)` includes an `add` row like `{type: 'add', oldPos: 3, newPos: 3, items: ['foo']}` and when I do `diff.applyPatch(newVal, patch)` it adds another `foo` at the end.

Example CodePen (also written out down below): https://codepen.io/master-elodin/pen/MWbKKGL

```java
import * as diff from "https://cdn.skypack.dev/fast-array-diff@1.0.0";

const oldVal = ['item1', 'item2', 'item3'];
const newVal = ['item4', 'item2', 'item3', 'foo'];

const patch = diff.getPatch(oldVal, newVal);
console.log(diff.applyPatch(newVal, patch));
// expected: ["item4", "item2", "item3", "foo"]
// actual: ["item4", "item2", "item3", "foo", "foo"]
```

**Comment by YuJianrong** [comment]
@master-elodin The function `diff.applyPatch` will apply the patch step by step **without check if the array is not the old array**, so it should not be called on any array except the old one. It **should not** and also **impossible** to check if the array called by `applyPatch` is the old array.

Working on `oldVal` only:
```javascript
console.log(diff.applyPatch(oldVal, patch));
```
