### ISSUE TITLE
Clarification on Array Sorting and Unsorted Input

### ISSUE THREAD

**Issue by abudayah** [YuJianrong/fast-array-diff#303]
I was recently looking into the source code and test cases of the `fast-array-diff` library and noticed that there doesn't appear to be any sorting applied to the input arrays during the comparison process. While testing the library, I encountered an issue where providing two identical arrays sorted differently resulted in incorrect results.

Is this behavior expected, or is it a bug? If it is expected, could you please provide some insights into why the library behaves this way and whether it is by design?

I believe it would be helpful to update the library's documentation with examples that clarify this behavior, as it can be crucial for users to understand how the library handles cases where input arrays are unsorted.

Thanks

**Comment by FishOrBear** [comment]
[1,2,3] and [3,2,1] are obviously different

**Comment by YuJianrong** [comment]
@abudayah This package is not used to find the diff of the **sets**, but diff of two sequences.
You can find [here](https://en.wikipedia.org/wiki/Longest_common_subsequence) for more details.
