### ISSUE TITLE
Array types shouldn't have to be the same

### ISSUE THREAD

**Issue by alexandrulesi** [YuJianrong/fast-array-diff#90]
Consider something like:

```
export interface DiffData<Ta, Tb> {
    removed: Ta[];
    added: Tb[];
}
export declare function diff<Ta, Tb>(a: Ta[], b: Tb[], compareFunc?: (ia: Ta, ib: Tb) => boolean): DiffData<Ta, Tb>;
```

My concrete use case is: I have some records in the db and new records coming in. The records in the db have `id`s, the new ones do not. I need the ids to know what records I want to archive in the db. Now I can't use this package without some workaround.

**Comment by YuJianrong** [comment]
WHy not just compare the content in `compareFunc`?
